// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function add(param, param$1) {
  return [
          param[0] + param$1[0],
          param[1] + param$1[1]
        ];
}

function scalarMultiply(param, s) {
  return [
          param[0] * s,
          param[1] * s
        ];
}

function length(param) {
  var y = param[1];
  var x = param[0];
  return Math.sqrt(x * x + y * y);
}

function normalize(vec) {
  var mag = length(vec);
  return [
          vec[0] / mag,
          vec[1] / mag
        ];
}

function midpoint(a, b) {
  return [
          (a[0] + b[0]) / 2,
          (a[1] + b[1]) / 2
        ];
}

function makePoints() {
  var center = [
    100,
    100
  ];
  var pts = [center];
  var offset = -90 * Math.PI / 180;
  var angle = 72 * Math.PI / 180;
  for(var i = 0; i <= 4; ++i){
    var x = Math.cos(angle * i + offset);
    var y = Math.sin(angle * i + offset);
    var p = add(scalarMultiply(normalize([
                  x,
                  y
                ]), 80), center);
    pts.push(p);
  }
  var triangles = [
    [
      0,
      1,
      2
    ],
    [
      0,
      2,
      3
    ],
    [
      0,
      3,
      4
    ],
    [
      0,
      4,
      5
    ],
    [
      0,
      5,
      1
    ]
  ];
  var p0 = pts[0];
  var p1 = pts[1];
  var p2 = pts[2];
  var p3 = pts[3];
  var p4 = pts[4];
  var p5 = pts[5];
  pts.push(midpoint(p0, p1));
  pts.push(midpoint(p0, p2));
  pts.push(midpoint(p0, p3));
  pts.push(midpoint(p0, p4));
  pts.push(midpoint(p0, p5));
  pts.push(midpoint(p1, p2));
  pts.push(midpoint(p2, p3));
  pts.push(midpoint(p3, p4));
  pts.push(midpoint(p4, p5));
  pts.push(midpoint(p5, p1));
  var foo = function (param) {
    var c = param[2];
    var b = param[1];
    var a = param[0];
    triangles.push([
          a,
          b,
          c
        ]);
    var pA = pts[a];
    var pB = pts[b];
    var pC = pts[c];
    pts.push(midpoint(pA, pB));
    pts.push(midpoint(pB, pC));
    pts.push(midpoint(pC, pA));
  };
  var subdivideFace = function (param) {
    var e = pts.length;
    var f = e + 1 | 0;
    var g = f + 1 | 0;
    var h = g + 1 | 0;
    var i = h + 1 | 0;
    var j = i + 1 | 0;
    foo([
          param[0],
          param[1],
          param[2]
        ]);
    foo([
          e,
          f,
          g
        ]);
    triangles.push([
          h,
          i,
          j
        ]);
  };
  subdivideFace([
        6,
        11,
        7
      ]);
  subdivideFace([
        7,
        12,
        8
      ]);
  subdivideFace([
        8,
        13,
        9
      ]);
  subdivideFace([
        9,
        14,
        10
      ]);
  subdivideFace([
        10,
        15,
        6
      ]);
  subdivideFace([
        0,
        6,
        7
      ]);
  subdivideFace([
        0,
        7,
        8
      ]);
  subdivideFace([
        0,
        8,
        9
      ]);
  subdivideFace([
        0,
        9,
        10
      ]);
  subdivideFace([
        0,
        10,
        6
      ]);
  subdivideFace([
        2,
        7,
        12
      ]);
  subdivideFace([
        12,
        3,
        8
      ]);
  subdivideFace([
        8,
        3,
        13
      ]);
  subdivideFace([
        13,
        4,
        9
      ]);
  subdivideFace([
        9,
        4,
        14
      ]);
  subdivideFace([
        10,
        14,
        5
      ]);
  subdivideFace([
        10,
        5,
        15
      ]);
  subdivideFace([
        6,
        15,
        1
      ]);
  subdivideFace([
        6,
        1,
        11
      ]);
  subdivideFace([
        7,
        11,
        2
      ]);
  return [
          pts,
          triangles
        ];
}

var colors = [
  "darkorchid",
  "deeppink",
  "firebrick"
];

var colorCount = colors.length;

function getColor(x) {
  return Core__Option.getOr(colors[Caml_int32.mod_(x + 2 | 0, colorCount)], "white");
}

function App(props) {
  var match = React.useMemo(makePoints, []);
  var points = match[0];
  return JsxRuntime.jsxs("svg", {
              children: [
                JsxRuntime.jsx("style", {
                      children: "text { font: 4px monospace; }"
                    }),
                match[1].map(function (triangle, i) {
                      var verts = [
                        triangle[0],
                        triangle[1],
                        triangle[2]
                      ];
                      var pts = verts.map(function (v) {
                              var match = points[v];
                              return match[0].toString() + "," + match[1].toString();
                            }).join(" ");
                      return JsxRuntime.jsx("polygon", {
                                  fill: "none",
                                  points: pts,
                                  stroke: getColor(i),
                                  strokeDasharray: "2 1 3",
                                  strokeOpacity: "0.75",
                                  strokeWidth: "0.5"
                                }, i.toString());
                    })
              ],
              className: "border rounded shadow-xl m-12",
              height: "600",
              width: "600",
              viewBox: "0 0 200 200"
            });
}

var make = App;

export {
  make ,
}
/* colorCount Not a pure module */
