// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "./Button.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function add(param, param$1) {
  return [
          param[0] + param$1[0],
          param[1] + param$1[1]
        ];
}

function scalarMultiply(param, s) {
  return [
          param[0] * s,
          param[1] * s
        ];
}

function length(param) {
  var y = param[1];
  var x = param[0];
  return Math.sqrt(x * x + y * y);
}

function normalize(vec) {
  var mag = length(vec);
  return [
          vec[0] / mag,
          vec[1] / mag
        ];
}

function makePoints() {
  var center = [
    100,
    100
  ];
  var pts = [center];
  var angle = 72 * Math.PI / 180;
  for(var i = 0; i <= 4; ++i){
    var x = Math.cos(angle * i);
    var y = Math.sin(angle * i);
    var p = add(scalarMultiply(normalize([
                  x,
                  y
                ]), 50), center);
    pts.push(p);
  }
  return pts;
}

function App(props) {
  var points = React.useMemo(makePoints, []);
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "What is this about?",
                      className: "text-3xl font-semibold"
                    }),
                JsxRuntime.jsx("p", {
                      children: "This is a simple template for a Vite project using ReScript & Tailwind CSS."
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Fast Refresh Test",
                      className: "text-2xl font-semibold mt-5"
                    }),
                JsxRuntime.jsx(Button.make, {
                      children: Caml_option.some("count is " + match[0].toString()),
                      onClick: (function (param) {
                          setCount(function (count) {
                                return count + 1 | 0;
                              });
                        })
                    }),
                JsxRuntime.jsxs("p", {
                      children: [
                        "Edit ",
                        JsxRuntime.jsx("code", {
                              children: "src/App.res"
                            }),
                        " and save to test Fast Refresh."
                      ]
                    }),
                JsxRuntime.jsxs("svg", {
                      children: [
                        JsxRuntime.jsx("style", {
                              children: "text { font: 10px monospace; }"
                            }),
                        points.map(function (param, i) {
                              var y = param[1];
                              var x = param[0];
                              return JsxRuntime.jsxs(React.Fragment, {
                                          children: [
                                            JsxRuntime.jsx("rect", {
                                                  height: "2",
                                                  width: "2",
                                                  fill: "black",
                                                  x: x.toString(),
                                                  y: y.toString()
                                                }),
                                            JsxRuntime.jsx("text", {
                                                  children: i.toString(),
                                                  x: (x + 4).toString(),
                                                  y: (y - 2).toString()
                                                })
                                          ]
                                        }, i.toString());
                            })
                      ],
                      className: "border",
                      height: "400",
                      width: "400",
                      viewBox: "0 0 200 200"
                    })
              ],
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
