// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function add(param, param$1) {
  return [
          param[0] + param$1[0],
          param[1] + param$1[1]
        ];
}

function scalarMultiply(param, s) {
  return [
          param[0] * s,
          param[1] * s
        ];
}

function length(param) {
  var y = param[1];
  var x = param[0];
  return Math.sqrt(x * x + y * y);
}

function normalize(vec) {
  var mag = length(vec);
  return [
          vec[0] / mag,
          vec[1] / mag
        ];
}

function makePoints() {
  var center = [
    100,
    100
  ];
  var pts = [center];
  var angle = 72 * Math.PI / 180;
  for(var i = 0; i <= 4; ++i){
    var x = Math.cos(angle * i);
    var y = Math.sin(angle * i);
    var p = add(scalarMultiply(normalize([
                  x,
                  y
                ]), 50), center);
    pts.push(p);
  }
  var triangles = [
    [
      0,
      1,
      2
    ],
    [
      0,
      2,
      3
    ],
    [
      0,
      3,
      4
    ],
    [
      0,
      4,
      5
    ],
    [
      0,
      5,
      1
    ]
  ];
  return [
          pts,
          triangles
        ];
}

function App(props) {
  var match = React.useMemo(makePoints, []);
  var points = match[0];
  return JsxRuntime.jsxs("svg", {
              children: [
                JsxRuntime.jsx("style", {
                      children: "text { font: 10px monospace; }"
                    }),
                match[1].map(function (triangle, i) {
                      var verts = [
                        triangle[0],
                        triangle[1],
                        triangle[2]
                      ];
                      var pts = verts.map(function (v) {
                              var match = points[v];
                              return match[0].toString() + "," + match[1].toString();
                            }).join(" ");
                      return JsxRuntime.jsx("polygon", {
                                  fill: "none",
                                  points: pts,
                                  stroke: "black"
                                }, i.toString());
                    }),
                points.map(function (param, i) {
                      var y = param[1];
                      var x = param[0];
                      return JsxRuntime.jsxs(React.Fragment, {
                                  children: [
                                    JsxRuntime.jsx("rect", {
                                          height: "2",
                                          width: "2",
                                          fill: "red",
                                          x: (x - 1).toString(),
                                          y: (y - 1).toString()
                                        }),
                                    JsxRuntime.jsx("text", {
                                          children: i.toString(),
                                          x: (x + 4).toString(),
                                          y: (y - 2).toString()
                                        })
                                  ]
                                }, i.toString());
                    })
              ],
              className: "border",
              height: "400",
              width: "400",
              viewBox: "0 0 200 200"
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
