// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml from "rescript/lib/es6/caml.js";
import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

var saturn = {
  diameter: 120500000,
  mass: 568300000000000000000000000n,
  x: 0,
  y: 0,
  velocityX: 0,
  velocityY: 0
};

var titan = {
  diameter: 5149000,
  mass: 135000000000000000000000n,
  x: 1221870,
  y: 0,
  velocityX: 0,
  velocityY: 0
};

var satcaster = {
  diameter: 2,
  mass: 800n,
  x: 125529,
  y: 0,
  velocityX: 0,
  velocityY: 17
};

function use() {
  var match = React.useReducer((function (state, action) {
          var bodies$p = state.bodies.map(function (entity) {
                if (entity.TAG === "Static") {
                  return {
                          TAG: "Static",
                          _0: entity._0
                        };
                }
                var body = entity._0;
                return {
                        TAG: "Dynamic",
                        _0: {
                          diameter: body.diameter,
                          mass: body.mass,
                          x: body.x + Math.imul(body.velocityX, 1000) | 0,
                          y: body.y + Math.imul(body.velocityY, 1000) | 0,
                          velocityX: body.velocityX,
                          velocityY: body.velocityY
                        }
                      };
              });
          return {
                  bodies: bodies$p
                };
        }), {
        bodies: [
          {
            TAG: "Static",
            _0: saturn
          },
          {
            TAG: "Dynamic",
            _0: titan
          },
          {
            TAG: "Dynamic",
            _0: satcaster
          }
        ]
      });
  return [
          match[0],
          match[1]
        ];
}

console.log(saturn, titan, satcaster);

function App(props) {
  var match = use();
  var dispatch = match[1];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("button", {
                      children: "Step",
                      type: "button",
                      onClick: (function (_e) {
                          dispatch("Step");
                        })
                    }),
                JsxRuntime.jsx("svg", {
                      children: match[0].bodies.map(function (entity) {
                              return entity._0;
                            }).map(function (body) {
                            var xOffset = Math.imul(body.x, 1000) / 2900000 | 0;
                            var yOffset = Math.imul(body.y, 1000) / 2900000 | 0;
                            var cx = 500 + xOffset | 0;
                            var cy = 500 + yOffset | 0;
                            var r = Caml.int_max(1, body.diameter / 2900000 | 0).toString();
                            return JsxRuntime.jsx("ellipse", {
                                        cx: cx.toString(),
                                        cy: cy.toString(),
                                        fill: "black",
                                        rx: r,
                                        ry: r
                                      });
                          }),
                      className: "border",
                      height: "1000",
                      width: "1200",
                      viewBox: "0 0 1000 1000"
                    })
              ],
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
